using System;
using System.Collections.Generic;
using System.Text;

namespace ConsoleApp1.Model
{
    public class Node
    {
        /// <summary>
        /// Magic square generated an specific node.
        /// </summary>
        public int[,] MagicSquare { get; set; }

        /// <summary>
        /// List of child nodes, meaning possible paths for the algorithm to choose.
        /// </summary>
        public List<Node> Childs{ get; set; }

        /// <summary>
        /// List of possible values to be choose as childs.
        /// </summary>
        public List<int> ValuesRow { get; set; }

        /// <summary>
        /// Constructor used when there's no magicsquare or values to be choose, meaning the tree's root.
        /// </summary>
        public Node()
        {
            Childs = new List<Node>();
            ValuesRow = new List<int>();
        }

        /// <summary>
        /// Constructor used for any node besides tree's root.
        /// </summary>
        /// <param name="magicSquare">Magic square generated by the node to be created.</param>
        /// <param name="valuesRow">List of possible values for this node's childs.</param>
        public Node(int[,] magicSquare, List<int> valuesRow)
        {
            MagicSquare = magicSquare;
            ValuesRow = valuesRow;
            Childs = new List<Node>();
        }
    }
}
