using System;
using System.Collections.Generic;
using System.Text;

namespace ConsoleApp1.Model
{
    public class Report
    {
        /// <summary>
        /// Magic square generated by the algorithm.
        /// </summary>
        public int[,] MagicSquare { get; set; }

        /// <summary>
        /// Total amount of time expent by the algorithm.
        /// </summary>
        public long ElapsedTime { get; set; }

        /// <summary>
        /// Name of the algorithm used.
        /// </summary>
        public string AlgorithmName { get; set; }
    }
}
